import type { Language } from '@/lib/i18n'

/**
 * Rótulo da categoria de vaga (`Job.category`) no idioma da tela.
 *
 * As 19 categorias e os nomes em português/inglês vêm do JobBase
 * (`job_categories`, avisado pelo time em 14-15/09/2026) — não inventados
 * aqui. `vaga_remota` é a 20ª, exclusiva do Griffo (ver `normalize.ts`):
 * regime de trabalho, não categoria de função, por isso não existe no
 * catálogo do JobBase.
 *
 * As 10 traduções restantes seguem a mesma ressalva já registrada para
 * toda a camada de i18n do projeto (pendência 21 do handoff): tom/registro
 * sem revisão por falante nativo. São palavras curtas de setor (não frase
 * de marketing), risco baixo mesmo assim.
 */
export const JOB_CATEGORY_SLUGS = [
  'ti',
  'engenharia',
  'marketing',
  'vendas',
  'transporte',
  'saude',
  'administrativo',
  'varejo_comercio',
  'financeiro',
  'recursos_humanos',
  'juridico',
  'logistica',
  'educacao',
  'design',
  'atendimento_ao_cliente',
  'operacoes',
  'producao_industrial',
  'construcao_civil',
  'vaga_remota',
  'outros',
] as const

export type JobCategorySlug = (typeof JOB_CATEGORY_SLUGS)[number]

const LABELS: Record<Language, Record<JobCategorySlug, string>> = {
  pt: {
    ti: 'Tecnologia da Informação',
    engenharia: 'Engenharia',
    marketing: 'Marketing',
    vendas: 'Vendas',
    transporte: 'Transporte',
    saude: 'Saúde',
    administrativo: 'Administrativo',
    varejo_comercio: 'Varejo e Comércio',
    financeiro: 'Financeiro',
    recursos_humanos: 'Recursos Humanos',
    juridico: 'Jurídico',
    logistica: 'Logística',
    educacao: 'Educação',
    design: 'Design',
    atendimento_ao_cliente: 'Atendimento ao Cliente',
    operacoes: 'Operações',
    producao_industrial: 'Produção e Manutenção Industrial',
    construcao_civil: 'Construção Civil',
    vaga_remota: 'Vaga Remota',
    outros: 'Outros',
  },
  en: {
    ti: 'Information Technology',
    engenharia: 'Engineering',
    marketing: 'Marketing',
    vendas: 'Sales',
    transporte: 'Transportation & Driving',
    saude: 'Healthcare',
    administrativo: 'Administrative',
    varejo_comercio: 'Retail',
    financeiro: 'Finance',
    recursos_humanos: 'Human Resources',
    juridico: 'Legal',
    logistica: 'Logistics & Supply Chain',
    educacao: 'Education',
    design: 'Design',
    atendimento_ao_cliente: 'Customer Support',
    operacoes: 'Operations',
    producao_industrial: 'Industrial Production & Maintenance',
    construcao_civil: 'Construction',
    vaga_remota: 'Remote Job',
    outros: 'Other',
  },
  es: {
    ti: 'Tecnología de la Información',
    engenharia: 'Ingeniería',
    marketing: 'Marketing',
    vendas: 'Ventas',
    transporte: 'Transporte',
    saude: 'Salud',
    administrativo: 'Administrativo',
    varejo_comercio: 'Comercio y Retail',
    financeiro: 'Finanzas',
    recursos_humanos: 'Recursos Humanos',
    juridico: 'Legal',
    logistica: 'Logística',
    educacao: 'Educación',
    design: 'Diseño',
    atendimento_ao_cliente: 'Atención al Cliente',
    operacoes: 'Operaciones',
    producao_industrial: 'Producción y Mantenimiento Industrial',
    construcao_civil: 'Construcción',
    vaga_remota: 'Empleo Remoto',
    outros: 'Otros',
  },
  de: {
    ti: 'Informationstechnologie',
    engenharia: 'Ingenieurwesen',
    marketing: 'Marketing',
    vendas: 'Vertrieb',
    transporte: 'Transport',
    saude: 'Gesundheitswesen',
    administrativo: 'Verwaltung',
    varejo_comercio: 'Einzelhandel',
    financeiro: 'Finanzen',
    recursos_humanos: 'Personalwesen',
    juridico: 'Recht',
    logistica: 'Logistik',
    educacao: 'Bildung',
    design: 'Design',
    atendimento_ao_cliente: 'Kundenservice',
    operacoes: 'Betrieb',
    producao_industrial: 'Industrielle Produktion und Wartung',
    construcao_civil: 'Bauwesen',
    vaga_remota: 'Remote-Job',
    outros: 'Sonstiges',
  },
  fr: {
    ti: "Technologies de l'Information",
    engenharia: 'Ingénierie',
    marketing: 'Marketing',
    vendas: 'Ventes',
    transporte: 'Transport',
    saude: 'Santé',
    administrativo: 'Administratif',
    varejo_comercio: 'Commerce de Détail',
    financeiro: 'Finance',
    recursos_humanos: 'Ressources Humaines',
    juridico: 'Juridique',
    logistica: 'Logistique',
    educacao: 'Éducation',
    design: 'Design',
    atendimento_ao_cliente: 'Service Client',
    operacoes: 'Opérations',
    producao_industrial: 'Production et Maintenance Industrielle',
    construcao_civil: 'Construction',
    vaga_remota: 'Emploi à Distance',
    outros: 'Autres',
  },
  it: {
    ti: "Tecnologia dell'Informazione",
    engenharia: 'Ingegneria',
    marketing: 'Marketing',
    vendas: 'Vendite',
    transporte: 'Trasporti',
    saude: 'Sanità',
    administrativo: 'Amministrativo',
    varejo_comercio: 'Commercio al Dettaglio',
    financeiro: 'Finanza',
    recursos_humanos: 'Risorse Umane',
    juridico: 'Legale',
    logistica: 'Logistica',
    educacao: 'Istruzione',
    design: 'Design',
    atendimento_ao_cliente: 'Assistenza Clienti',
    operacoes: 'Operazioni',
    producao_industrial: 'Produzione e Manutenzione Industriale',
    construcao_civil: 'Costruzioni',
    vaga_remota: 'Lavoro da Remoto',
    outros: 'Altro',
  },
  ja: {
    ti: '情報技術',
    engenharia: 'エンジニアリング',
    marketing: 'マーケティング',
    vendas: '営業',
    transporte: '運送',
    saude: '医療',
    administrativo: '総務',
    varejo_comercio: '小売',
    financeiro: '財務',
    recursos_humanos: '人事',
    juridico: '法務',
    logistica: '物流',
    educacao: '教育',
    design: 'デザイン',
    atendimento_ao_cliente: 'カスタマーサポート',
    operacoes: '運用',
    producao_industrial: '生産・設備保守',
    construcao_civil: '建設',
    vaga_remota: 'リモート勤務',
    outros: 'その他',
  },
  nl: {
    ti: 'Informatietechnologie',
    engenharia: 'Techniek',
    marketing: 'Marketing',
    vendas: 'Verkoop',
    transporte: 'Transport',
    saude: 'Gezondheidszorg',
    administrativo: 'Administratie',
    varejo_comercio: 'Retail',
    financeiro: 'Financiën',
    recursos_humanos: 'Human Resources',
    juridico: 'Juridisch',
    logistica: 'Logistiek',
    educacao: 'Onderwijs',
    design: 'Design',
    atendimento_ao_cliente: 'Klantenservice',
    operacoes: 'Operations',
    producao_industrial: 'Industriële Productie en Onderhoud',
    construcao_civil: 'Bouw',
    vaga_remota: 'Remote Werk',
    outros: 'Overig',
  },
  sv: {
    ti: 'Informationsteknik',
    engenharia: 'Teknik',
    marketing: 'Marknadsföring',
    vendas: 'Försäljning',
    transporte: 'Transport',
    saude: 'Hälso- och Sjukvård',
    administrativo: 'Administration',
    varejo_comercio: 'Detaljhandel',
    financeiro: 'Ekonomi',
    recursos_humanos: 'HR',
    juridico: 'Juridik',
    logistica: 'Logistik',
    educacao: 'Utbildning',
    design: 'Design',
    atendimento_ao_cliente: 'Kundtjänst',
    operacoes: 'Drift',
    producao_industrial: 'Industriell Produktion och Underhåll',
    construcao_civil: 'Bygg',
    vaga_remota: 'Distansjobb',
    outros: 'Övrigt',
  },
  zh: {
    ti: '信息技术',
    engenharia: '工程',
    marketing: '市场营销',
    vendas: '销售',
    transporte: '运输',
    saude: '医疗保健',
    administrativo: '行政',
    varejo_comercio: '零售',
    financeiro: '财务',
    recursos_humanos: '人力资源',
    juridico: '法务',
    logistica: '物流',
    educacao: '教育',
    design: '设计',
    atendimento_ao_cliente: '客户服务',
    operacoes: '运营',
    producao_industrial: '生产与设备维护',
    construcao_civil: '建筑施工',
    vaga_remota: '远程工作',
    outros: '其他',
  },
  ar: {
    ti: 'تكنولوجيا المعلومات',
    engenharia: 'الهندسة',
    marketing: 'التسويق',
    vendas: 'المبيعات',
    transporte: 'النقل',
    saude: 'الرعاية الصحية',
    administrativo: 'الإدارة',
    varejo_comercio: 'التجزئة',
    financeiro: 'المالية',
    recursos_humanos: 'الموارد البشرية',
    juridico: 'الشؤون القانونية',
    logistica: 'الخدمات اللوجستية',
    educacao: 'التعليم',
    design: 'التصميم',
    atendimento_ao_cliente: 'خدمة العملاء',
    operacoes: 'العمليات',
    producao_industrial: 'الإنتاج والصيانة الصناعية',
    construcao_civil: 'البناء',
    vaga_remota: 'وظيفة عن بُعد',
    outros: 'أخرى',
  },
  ko: {
    ti: '정보 기술',
    engenharia: '엔지니어링',
    marketing: '마케팅',
    vendas: '영업',
    transporte: '운송',
    saude: '의료',
    administrativo: '행정',
    varejo_comercio: '소매',
    financeiro: '재무',
    recursos_humanos: '인사',
    juridico: '법무',
    logistica: '물류',
    educacao: '교육',
    design: '디자인',
    atendimento_ao_cliente: '고객 지원',
    operacoes: '운영',
    producao_industrial: '생산 및 설비 유지보수',
    construcao_civil: '건설',
    vaga_remota: '원격 근무',
    outros: '기타',
  },
}

/** Rótulo da categoria no idioma pedido. Slug desconhecido cai em "outros"
 *  — nunca mostra o slug cru pra quem usa a tela. */
export function categoryLabel(slug: string, lang: Language): string {
  const table = LABELS[lang] ?? LABELS.en
  return table[slug as JobCategorySlug] ?? table.outros
}
