import type { Language } from '../i18n/types'
import type { OverallFit } from '../matching/compatibility'
import type { TeaserCategory } from './rules'

/**
 * Textos do envio de currículo no topo da landing (§2.132), nos 12 idiomas.
 *
 * O português é a fonte (decisões do operador de 23/09/2026). As outras 11
 * línguas são tradução dele e passam pelo agente `translation-reviewer`.
 *
 * Três regras que valem para qualquer ajuste aqui:
 *
 * - A isca quantifica e nunca revela: "3 pontos em formatação", nunca QUAIS
 *   (decisões 4 e 5 do §2.132).
 * - "Pode aumentar suas chances" e nunca uma promessa ou porcentagem (§17).
 *   A frase só aparece quando o teste achou ao menos um ponto: dizer a quem tem
 *   um currículo bom que ele precisa de conserto seria inventar (CDC art. 37).
 * - A opção de guardar dados diz "para que empresas possam te encontrar", e
 *   não que já estão procurando: a consulta por empresas ainda não existe como
 *   produto (ver §2.132, decisão 3 das respostas).
 *
 * Marcadores: {N} vagas abertas, {count} oportunidades, {n} número genérico,
 * {date} data formatada, {email} endereço de contato, {name} nome do arquivo.
 */
export interface MatchPreviewCopy {
  eyebrow: string
  title: string
  lead: string
  subtitle: string
  uploadCta: string
  fileChosen: string
  uploadHint: string
  pasteToggle: string
  pastePlaceholder: string
  emailLabel: string
  emailPlaceholder: string
  emailHint: string
  retentionTitle: string
  retentionDelete: string
  retentionDeleteHint: string
  retentionKeep: string
  retentionKeepHint: string
  privacyLink: string
  submitCta: string
  submitting: string
  processing: string
  processingHint: string
  errorEmail: string
  errorFile: string
  errorTooLarge: string
  errorNotPdf: string
  errorRate: string
  errorGeneric: string
  limitTitle: string
  limitText: string
  limitCta: string
  expiredText: string
  failedText: string
  retryCta: string
  resultTitleMany: string
  resultTitleOne: string
  resultTitleNone: string
  resultNoneText: string
  profileInsufficientText: string
  freeBadge: string
  fit: Record<OverallFit, string>
  remote: { remote: string; hybrid: string; onsite: string }
  publishedOn: string
  applyCta: string
  applyNote: string
  lockedTitle: string
  lockedTitleOne: string
  lockedStrong: string
  lockedStrongOne: string
  unlockCta: string
  atsScoreLabel: string
  teaserMany: string
  teaserOne: string
  teaserNone: string
  teaserCategories: Record<TeaserCategory, string>
  teaserClose: string
  teaserCta: string
  keptNote: string
  deleteNote: string
  emailSubject: string
  emailHeading: string
  emailBodyMatches: string
  emailBodyOne: string
  emailBodyNone: string
  emailCta: string
  emailDeleteNote: string
  emailKeepNote: string
  emailIgnore: string
}

const pt: MatchPreviewCopy = {
  eyebrow: 'Grátis · sem cadastro',
  title: 'Procurando emprego?',
  lead: 'Envie seu currículo e descubra as oportunidades que combinam com você.',
  subtitle: 'Comparamos seu currículo com {N} vagas abertas e mostramos onde você se encaixa.',
  uploadCta: 'Escolher currículo em PDF',
  fileChosen: 'Arquivo: {name}',
  uploadHint: 'PDF de até 5 MB',
  pasteToggle: 'Prefiro colar o texto',
  pastePlaceholder: 'Cole aqui o texto do seu currículo…',
  emailLabel: 'Seu e-mail',
  emailPlaceholder: 'voce@email.com',
  emailHint: 'Mandamos o link do resultado para este e-mail.',
  retentionTitle: 'O que fazemos com seus dados',
  retentionDelete: 'Apagar tudo em até 24 horas',
  retentionDeleteHint: 'Você vê o resultado e depois não guardamos nada.',
  retentionKeep: 'Guardar meu currículo para que empresas possam me encontrar',
  retentionKeepHint: 'Fica guardado por até 2 anos, e você pode pedir para apagar quando quiser.',
  privacyLink: 'Política de privacidade',
  submitCta: 'Encontrar minhas oportunidades',
  submitting: 'Enviando seu currículo…',
  processing: 'Comparando seu perfil com as vagas abertas…',
  processingHint: 'Leva alguns segundos. Não feche esta página.',
  errorEmail: 'Confira o e-mail.',
  errorFile: 'Escolha um PDF ou cole o texto do currículo.',
  errorTooLarge: 'O arquivo passa de 5 MB.',
  errorNotPdf: 'Esse arquivo não é um PDF válido.',
  errorRate: 'Muitas tentativas seguidas. Espere alguns minutos.',
  errorGeneric: 'Algo deu errado do nosso lado. Tente de novo em instantes.',
  limitTitle: 'Você já usou a busca grátis de hoje',
  limitText: 'Crie sua conta para continuar agora, ou volte amanhã.',
  limitCta: 'Criar conta',
  expiredText: 'Este resultado expirou e os dados foram apagados.',
  failedText: 'Não conseguimos ler seu currículo agora. Tente de novo em instantes.',
  retryCta: 'Enviar de novo',
  resultTitleMany: 'Encontramos {count} oportunidades que combinam com você',
  resultTitleOne: 'Encontramos 1 oportunidade que combina com você',
  resultTitleNone: 'Ainda não encontramos uma oportunidade forte para o seu perfil',
  resultNoneText: 'As vagas mudam todo dia. Com uma conta, o Radar avisa você quando aparecer uma que combine.',
  profileInsufficientText: 'Não identificamos no currículo seu cargo, sua área ou suas competências, então ainda não há o que comparar com as vagas.',
  freeBadge: 'Oportunidade liberada',
  fit: {
    strong: 'Alta compatibilidade',
    good: 'Boa compatibilidade',
    partial: 'Compatibilidade parcial',
    weak: 'Baixa compatibilidade',
  },
  remote: { remote: 'Remoto', hybrid: 'Híbrido', onsite: 'Presencial' },
  publishedOn: 'Publicada em {date}',
  applyCta: 'Ver a vaga e se candidatar',
  applyNote: 'A candidatura é feita no site de origem da vaga.',
  lockedTitle: 'Há mais {count} oportunidades com o seu perfil',
  lockedTitleOne: 'Há mais 1 oportunidade com o seu perfil',
  lockedStrong: '{n} delas com alta compatibilidade',
  lockedStrongOne: 'e ela é de alta compatibilidade',
  unlockCta: 'Ver todas as oportunidades',
  atsScoreLabel: 'Legibilidade para sistemas de triagem',
  teaserMany: 'Encontramos {n} pontos que reduzem sua visibilidade nos sistemas de triagem',
  teaserOne: 'Encontramos 1 ponto que reduz sua visibilidade nos sistemas de triagem',
  teaserNone: 'Seu currículo é bem lido pelos sistemas de triagem.',
  teaserCategories: {
    keywords: '{n} em palavras-chave e conteúdo',
    formatting: '{n} em formatação',
    experience: '{n} em experiência e formação',
    contact: '{n} em dados de contato',
  },
  teaserClose: 'Corrigir pode aumentar suas chances de receber convites para entrevista.',
  teaserCta: 'Ver o diagnóstico completo',
  keptNote: 'Seu currículo ficou guardado para empresas te encontrarem. Para apagar, escreva para {email}.',
  deleteNote: 'Seus dados serão apagados em até 24 horas.',
  emailSubject: 'Seu resultado na GriffoWork',
  emailHeading: 'Seu resultado está pronto',
  emailBodyMatches: 'Encontramos {count} oportunidades que combinam com o seu currículo.',
  emailBodyOne: 'Encontramos 1 oportunidade que combina com o seu currículo.',
  emailBodyNone: 'Lemos seu currículo e o resultado está pronto.',
  emailCta: 'Ver meu resultado',
  emailDeleteNote: 'Seus dados serão apagados em até 24 horas, e o link deixa de funcionar antes disso.',
  emailKeepNote: 'Você escolheu guardar seu currículo para empresas te encontrarem. Para apagar, responda este e-mail.',
  emailIgnore: 'Se não foi você que enviou, pode ignorar este e-mail.',
}

const en: MatchPreviewCopy = {
  eyebrow: 'Free · no sign-up',
  title: 'Looking for a job?',
  lead: 'Upload your resume and discover the opportunities that match you.',
  subtitle: 'We compare your resume with {N} open jobs and show you where you fit.',
  uploadCta: 'Choose resume PDF',
  fileChosen: 'File: {name}',
  uploadHint: 'PDF up to 5 MB',
  pasteToggle: "I'd rather paste the text",
  pastePlaceholder: 'Paste your resume text here…',
  emailLabel: 'Your email',
  emailPlaceholder: 'you@email.com',
  emailHint: "We'll send the link to your results to this address.",
  retentionTitle: 'What we do with your data',
  retentionDelete: 'Delete everything within 24 hours',
  retentionDeleteHint: 'You see your results, and then we keep nothing.',
  retentionKeep: 'Keep my resume so companies can find me',
  retentionKeepHint: 'Kept for up to 2 years, and you can ask us to delete it at any time.',
  privacyLink: 'Privacy policy',
  submitCta: 'Find my opportunities',
  submitting: 'Uploading your resume…',
  processing: 'Comparing your profile with open jobs…',
  processingHint: 'This takes a few seconds. Please keep this page open.',
  errorEmail: 'Please check your email address.',
  errorFile: 'Choose a PDF or paste your resume text.',
  errorTooLarge: 'The file is larger than 5 MB.',
  errorNotPdf: "This file isn't a valid PDF.",
  errorRate: 'Too many attempts in a row. Please wait a few minutes.',
  errorGeneric: 'Something went wrong on our side. Please try again shortly.',
  limitTitle: "You've already used today's free search",
  limitText: 'Create your account to keep going now, or come back tomorrow.',
  limitCta: 'Create account',
  expiredText: 'These results have expired and the data has been deleted.',
  failedText: "We couldn't read your resume right now. Please try again shortly.",
  retryCta: 'Upload again',
  resultTitleMany: 'We found {count} opportunities that match you',
  resultTitleOne: 'We found 1 opportunity that matches you',
  resultTitleNone: "We haven't found a strong opportunity for your profile yet",
  resultNoneText: 'Jobs change every day. With an account, Radar tells you when one that matches shows up.',
  profileInsufficientText: "We couldn't find your job title, field or skills in the resume, so there's nothing to compare with the jobs yet.",
  freeBadge: 'Unlocked opportunity',
  fit: {
    strong: 'High match',
    good: 'Good match',
    partial: 'Partial match',
    weak: 'Low match',
  },
  remote: { remote: 'Remote', hybrid: 'Hybrid', onsite: 'On-site' },
  publishedOn: 'Posted on {date}',
  applyCta: 'View the job and apply',
  applyNote: "You apply on the job's original website.",
  lockedTitle: 'There are {count} more opportunities for your profile',
  lockedTitleOne: 'There is 1 more opportunity for your profile',
  lockedStrong: '{n} of them are a high match',
  lockedStrongOne: 'and it is a high match',
  unlockCta: 'See all opportunities',
  atsScoreLabel: 'Readability for screening systems',
  teaserMany: 'We found {n} issues that reduce your visibility in screening systems',
  teaserOne: 'We found 1 issue that reduces your visibility in screening systems',
  teaserNone: 'Screening systems read your resume well.',
  teaserCategories: {
    keywords: '{n} in keywords and content',
    formatting: '{n} in formatting',
    experience: '{n} in experience and education',
    contact: '{n} in contact details',
  },
  teaserClose: 'Fixing them can improve your chances of being invited to an interview.',
  teaserCta: 'See the full diagnosis',
  keptNote: 'Your resume has been kept so companies can find you. To delete it, write to {email}.',
  deleteNote: 'Your data will be deleted within 24 hours.',
  emailSubject: 'Your GriffoWork results',
  emailHeading: 'Your results are ready',
  emailBodyMatches: 'We found {count} opportunities that match your resume.',
  emailBodyOne: 'We found 1 opportunity that matches your resume.',
  emailBodyNone: 'We read your resume and your results are ready.',
  emailCta: 'See my results',
  emailDeleteNote: 'Your data will be deleted within 24 hours, and the link stops working before then.',
  emailKeepNote: 'You chose to keep your resume so companies can find you. To delete it, reply to this email.',
  emailIgnore: "If you didn't submit this, you can ignore this email.",
}

const es: MatchPreviewCopy = {
  eyebrow: 'Gratis · sin registro',
  title: '¿Buscas empleo?',
  lead: 'Envía tu currículum y descubre las oportunidades que encajan contigo.',
  subtitle: 'Comparamos tu currículum con {N} ofertas abiertas y te mostramos dónde encajas.',
  uploadCta: 'Elegir currículum en PDF',
  fileChosen: 'Archivo: {name}',
  uploadHint: 'PDF de hasta 5 MB',
  pasteToggle: 'Prefiero pegar el texto',
  pastePlaceholder: 'Pega aquí el texto de tu currículum…',
  emailLabel: 'Tu correo electrónico',
  emailPlaceholder: 'tu@correo.com',
  emailHint: 'Te enviamos el enlace del resultado a este correo.',
  retentionTitle: 'Qué hacemos con tus datos',
  retentionDelete: 'Borrar todo en un plazo de 24 horas',
  retentionDeleteHint: 'Ves el resultado y después no guardamos nada.',
  retentionKeep: 'Guardar mi currículum para que las empresas puedan encontrarme',
  retentionKeepHint: 'Se guarda hasta 2 años, y puedes pedir que lo borremos cuando quieras.',
  privacyLink: 'Política de privacidad',
  submitCta: 'Encontrar mis oportunidades',
  submitting: 'Enviando tu currículum…',
  processing: 'Comparando tu perfil con las ofertas abiertas…',
  processingHint: 'Tarda unos segundos. No cierres esta página.',
  errorEmail: 'Revisa el correo electrónico.',
  errorFile: 'Elige un PDF o pega el texto del currículum.',
  errorTooLarge: 'El archivo supera los 5 MB.',
  errorNotPdf: 'Este archivo no es un PDF válido.',
  errorRate: 'Demasiados intentos seguidos. Espera unos minutos.',
  errorGeneric: 'Algo falló de nuestro lado. Inténtalo de nuevo en unos instantes.',
  limitTitle: 'Ya usaste la búsqueda gratuita de hoy',
  limitText: 'Crea tu cuenta para seguir ahora, o vuelve mañana.',
  limitCta: 'Crear cuenta',
  expiredText: 'Este resultado caducó y los datos se borraron.',
  failedText: 'No pudimos leer tu currículum ahora. Inténtalo de nuevo en unos instantes.',
  retryCta: 'Enviar de nuevo',
  resultTitleMany: 'Encontramos {count} oportunidades que encajan contigo',
  resultTitleOne: 'Encontramos 1 oportunidad que encaja contigo',
  resultTitleNone: 'Aún no encontramos una oportunidad sólida para tu perfil',
  resultNoneText: 'Las ofertas cambian cada día. Con una cuenta, el Radar te avisa cuando aparezca una que encaje.',
  profileInsufficientText: 'No identificamos en el currículum tu cargo, tu área ni tus competencias, así que todavía no hay nada que comparar con las ofertas.',
  freeBadge: 'Oportunidad desbloqueada',
  fit: {
    strong: 'Alta compatibilidad',
    good: 'Buena compatibilidad',
    partial: 'Compatibilidad parcial',
    weak: 'Baja compatibilidad',
  },
  remote: { remote: 'Remoto', hybrid: 'Híbrido', onsite: 'Presencial' },
  publishedOn: 'Publicada el {date}',
  applyCta: 'Ver la oferta y postularme',
  applyNote: 'La postulación se hace en el sitio de origen de la oferta.',
  lockedTitle: 'Hay {count} oportunidades más con tu perfil',
  lockedTitleOne: 'Hay 1 oportunidad más con tu perfil',
  lockedStrong: '{n} de ellas con alta compatibilidad',
  lockedStrongOne: 'y es de alta compatibilidad',
  unlockCta: 'Ver todas las oportunidades',
  atsScoreLabel: 'Legibilidad para sistemas de selección',
  teaserMany: 'Encontramos {n} puntos que reducen tu visibilidad en los sistemas de selección',
  teaserOne: 'Encontramos 1 punto que reduce tu visibilidad en los sistemas de selección',
  teaserNone: 'Los sistemas de selección leen bien tu currículum.',
  teaserCategories: {
    keywords: '{n} en palabras clave y contenido',
    formatting: '{n} en formato',
    experience: '{n} en experiencia y formación',
    contact: '{n} en datos de contacto',
  },
  teaserClose: 'Corregirlos puede aumentar tus posibilidades de que te llamen a una entrevista.',
  teaserCta: 'Ver el diagnóstico completo',
  keptNote: 'Tu currículum quedó guardado para que las empresas te encuentren. Para borrarlo, escribe a {email}.',
  deleteNote: 'Tus datos se borrarán en un plazo de 24 horas.',
  emailSubject: 'Tu resultado en GriffoWork',
  emailHeading: 'Tu resultado está listo',
  emailBodyMatches: 'Encontramos {count} oportunidades que encajan con tu currículum.',
  emailBodyOne: 'Encontramos 1 oportunidad que encaja con tu currículum.',
  emailBodyNone: 'Leímos tu currículum y el resultado está listo.',
  emailCta: 'Ver mi resultado',
  emailDeleteNote: 'Tus datos se borrarán en un plazo de 24 horas, y el enlace deja de funcionar antes.',
  emailKeepNote: 'Elegiste guardar tu currículum para que las empresas te encuentren. Para borrarlo, responde a este correo.',
  emailIgnore: 'Si no fuiste tú quien lo envió, puedes ignorar este correo.',
}

const de: MatchPreviewCopy = {
  eyebrow: 'Kostenlos · ohne Anmeldung',
  title: 'Auf Jobsuche?',
  lead: 'Laden Sie Ihren Lebenslauf hoch und entdecken Sie die Chancen, die zu Ihnen passen.',
  subtitle: 'Wir vergleichen Ihren Lebenslauf mit {N} offenen Stellen und zeigen Ihnen, wo Sie passen.',
  uploadCta: 'Lebenslauf als PDF auswählen',
  fileChosen: 'Datei: {name}',
  uploadHint: 'PDF bis 5 MB',
  pasteToggle: 'Ich füge lieber den Text ein',
  pastePlaceholder: 'Fügen Sie hier den Text Ihres Lebenslaufs ein…',
  emailLabel: 'Ihre E-Mail-Adresse',
  emailPlaceholder: 'sie@email.de',
  emailHint: 'Wir senden den Link zu Ihrem Ergebnis an diese Adresse.',
  retentionTitle: 'Was wir mit Ihren Daten machen',
  retentionDelete: 'Alles innerhalb von 24 Stunden löschen',
  retentionDeleteHint: 'Sie sehen Ihr Ergebnis, danach speichern wir nichts.',
  retentionKeep: 'Meinen Lebenslauf speichern, damit Unternehmen mich finden können',
  retentionKeepHint: 'Wird bis zu 2 Jahre gespeichert, und Sie können die Löschung jederzeit verlangen.',
  privacyLink: 'Datenschutzerklärung',
  submitCta: 'Meine Chancen finden',
  submitting: 'Ihr Lebenslauf wird hochgeladen…',
  processing: 'Wir vergleichen Ihr Profil mit den offenen Stellen…',
  processingHint: 'Das dauert einige Sekunden. Bitte schließen Sie diese Seite nicht.',
  errorEmail: 'Bitte prüfen Sie die E-Mail-Adresse.',
  errorFile: 'Wählen Sie ein PDF oder fügen Sie den Text Ihres Lebenslaufs ein.',
  errorTooLarge: 'Die Datei ist größer als 5 MB.',
  errorNotPdf: 'Diese Datei ist kein gültiges PDF.',
  errorRate: 'Zu viele Versuche hintereinander. Bitte warten Sie einige Minuten.',
  errorGeneric: 'Bei uns ist etwas schiefgelaufen. Bitte versuchen Sie es gleich noch einmal.',
  limitTitle: 'Sie haben die kostenlose Suche für heute schon genutzt',
  limitText: 'Erstellen Sie ein Konto, um jetzt weiterzumachen, oder kommen Sie morgen wieder.',
  limitCta: 'Konto erstellen',
  expiredText: 'Dieses Ergebnis ist abgelaufen, und die Daten wurden gelöscht.',
  failedText: 'Wir konnten Ihren Lebenslauf gerade nicht lesen. Bitte versuchen Sie es gleich noch einmal.',
  retryCta: 'Erneut hochladen',
  resultTitleMany: 'Wir haben {count} Chancen gefunden, die zu Ihnen passen',
  resultTitleOne: 'Wir haben 1 Chance gefunden, die zu Ihnen passt',
  resultTitleNone: 'Wir haben noch keine starke Chance für Ihr Profil gefunden',
  resultNoneText: 'Stellen ändern sich jeden Tag. Mit einem Konto meldet sich der Radar, sobald eine passende auftaucht.',
  profileInsufficientText: 'Wir konnten in Ihrem Lebenslauf weder Ihre Position noch Ihr Fachgebiet oder Ihre Kompetenzen erkennen, daher gibt es noch nichts mit den Stellen zu vergleichen.',
  freeBadge: 'Freigeschaltete Chance',
  fit: {
    strong: 'Hohe Übereinstimmung',
    good: 'Gute Übereinstimmung',
    partial: 'Teilweise Übereinstimmung',
    weak: 'Geringe Übereinstimmung',
  },
  remote: { remote: 'Remote', hybrid: 'Hybrid', onsite: 'Vor Ort' },
  publishedOn: 'Veröffentlicht am {date}',
  applyCta: 'Stelle ansehen und bewerben',
  applyNote: 'Die Bewerbung erfolgt auf der Originalseite der Stelle.',
  lockedTitle: 'Es gibt {count} weitere Chancen für Ihr Profil',
  lockedTitleOne: 'Es gibt 1 weitere Chance für Ihr Profil',
  lockedStrong: '{n} davon mit hoher Übereinstimmung',
  lockedStrongOne: 'mit hoher Übereinstimmung',
  unlockCta: 'Alle Chancen ansehen',
  atsScoreLabel: 'Lesbarkeit für Bewerbermanagementsysteme',
  teaserMany: 'Wir haben {n} Punkte gefunden, die Ihre Sichtbarkeit in Bewerbermanagementsystemen verringern',
  teaserOne: 'Wir haben 1 Punkt gefunden, der Ihre Sichtbarkeit in Bewerbermanagementsystemen verringert',
  teaserNone: 'Bewerbermanagementsysteme lesen Ihren Lebenslauf gut.',
  teaserCategories: {
    keywords: '{n} bei Schlüsselwörtern und Inhalt',
    formatting: '{n} bei der Formatierung',
    experience: '{n} bei Berufserfahrung und Ausbildung',
    contact: '{n} bei den Kontaktdaten',
  },
  teaserClose: 'Wenn Sie sie beheben, kann das Ihre Chancen auf eine Einladung zum Vorstellungsgespräch verbessern.',
  teaserCta: 'Vollständige Diagnose ansehen',
  keptNote: 'Ihr Lebenslauf wurde gespeichert, damit Unternehmen Sie finden können. Zum Löschen schreiben Sie an {email}.',
  deleteNote: 'Ihre Daten werden innerhalb von 24 Stunden gelöscht.',
  emailSubject: 'Ihr Ergebnis bei GriffoWork',
  emailHeading: 'Ihr Ergebnis ist fertig',
  emailBodyMatches: 'Wir haben {count} Chancen gefunden, die zu Ihrem Lebenslauf passen.',
  emailBodyOne: 'Wir haben 1 Chance gefunden, die zu Ihrem Lebenslauf passt.',
  emailBodyNone: 'Wir haben Ihren Lebenslauf gelesen, und Ihr Ergebnis ist fertig.',
  emailCta: 'Mein Ergebnis ansehen',
  emailDeleteNote: 'Ihre Daten werden innerhalb von 24 Stunden gelöscht, und der Link funktioniert schon vorher nicht mehr.',
  emailKeepNote: 'Sie haben gewählt, Ihren Lebenslauf zu speichern, damit Unternehmen Sie finden können. Zum Löschen antworten Sie auf diese E-Mail.',
  emailIgnore: 'Wenn Sie das nicht waren, können Sie diese E-Mail ignorieren.',
}

const fr: MatchPreviewCopy = {
  eyebrow: 'Gratuit · sans inscription',
  title: 'Vous cherchez un emploi ?',
  lead: 'Envoyez votre CV et découvrez les opportunités qui vous correspondent.',
  subtitle: 'Nous comparons votre CV à {N} offres ouvertes et vous montrons où vous correspondez.',
  uploadCta: 'Choisir un CV en PDF',
  fileChosen: 'Fichier : {name}',
  uploadHint: 'PDF jusqu’à 5 Mo',
  pasteToggle: 'Je préfère coller le texte',
  pastePlaceholder: 'Collez ici le texte de votre CV…',
  emailLabel: 'Votre e-mail',
  emailPlaceholder: 'vous@email.fr',
  emailHint: 'Nous envoyons le lien de votre résultat à cette adresse.',
  retentionTitle: 'Ce que nous faisons de vos données',
  retentionDelete: 'Tout supprimer sous 24 heures',
  retentionDeleteHint: 'Vous voyez votre résultat, puis nous ne gardons rien.',
  retentionKeep: 'Conserver mon CV pour que des entreprises puissent me trouver',
  retentionKeepHint: 'Conservé jusqu’à 2 ans, et vous pouvez en demander la suppression à tout moment.',
  privacyLink: 'Politique de confidentialité',
  submitCta: 'Trouver mes opportunités',
  submitting: 'Envoi de votre CV…',
  processing: 'Nous comparons votre profil aux offres ouvertes…',
  processingHint: 'Cela prend quelques secondes. Ne fermez pas cette page.',
  errorEmail: 'Vérifiez votre adresse e-mail.',
  errorFile: 'Choisissez un PDF ou collez le texte de votre CV.',
  errorTooLarge: 'Le fichier dépasse 5 Mo.',
  errorNotPdf: 'Ce fichier n’est pas un PDF valide.',
  errorRate: 'Trop de tentatives d’affilée. Patientez quelques minutes.',
  errorGeneric: 'Un problème est survenu de notre côté. Réessayez dans quelques instants.',
  limitTitle: 'Vous avez déjà utilisé la recherche gratuite du jour',
  limitText: 'Créez votre compte pour continuer maintenant, ou revenez demain.',
  limitCta: 'Créer un compte',
  expiredText: 'Ce résultat a expiré et les données ont été supprimées.',
  failedText: 'Nous n’avons pas pu lire votre CV pour le moment. Réessayez dans quelques instants.',
  retryCta: 'Envoyer à nouveau',
  resultTitleMany: 'Nous avons trouvé {count} opportunités qui vous correspondent',
  resultTitleOne: 'Nous avons trouvé 1 opportunité qui vous correspond',
  resultTitleNone: 'Nous n’avons pas encore trouvé d’opportunité solide pour votre profil',
  resultNoneText: 'Les offres changent chaque jour. Avec un compte, le Radar vous prévient dès qu’une offre qui vous correspond apparaît.',
  profileInsufficientText: 'Nous n’avons trouvé dans votre CV ni votre poste, ni votre domaine, ni vos compétences : il n’y a donc encore rien à comparer avec les offres.',
  freeBadge: 'Opportunité débloquée',
  fit: {
    strong: 'Forte compatibilité',
    good: 'Bonne compatibilité',
    partial: 'Compatibilité partielle',
    weak: 'Faible compatibilité',
  },
  remote: { remote: 'Télétravail', hybrid: 'Hybride', onsite: 'Sur site' },
  publishedOn: 'Publiée le {date}',
  applyCta: 'Voir l’offre et postuler',
  applyNote: 'La candidature se fait sur le site d’origine de l’offre.',
  lockedTitle: 'Il y a {count} autres opportunités pour votre profil',
  lockedTitleOne: 'Il y a 1 autre opportunité pour votre profil',
  lockedStrong: 'dont {n} avec une forte compatibilité',
  lockedStrongOne: 'avec une forte compatibilité',
  unlockCta: 'Voir toutes les opportunités',
  atsScoreLabel: 'Lisibilité pour les logiciels de recrutement',
  teaserMany: 'Nous avons trouvé {n} points qui réduisent votre visibilité dans les logiciels de recrutement',
  teaserOne: 'Nous avons trouvé 1 point qui réduit votre visibilité dans les logiciels de recrutement',
  teaserNone: 'Les logiciels de recrutement lisent bien votre CV.',
  teaserCategories: {
    keywords: '{n} dans les mots-clés et le contenu',
    formatting: '{n} dans la mise en forme',
    experience: '{n} dans l’expérience et la formation',
    contact: '{n} dans les coordonnées',
  },
  teaserClose: 'Les corriger peut augmenter vos chances d’obtenir un entretien.',
  teaserCta: 'Voir le diagnostic complet',
  keptNote: 'Votre CV a été conservé pour que des entreprises puissent vous trouver. Pour le supprimer, écrivez à {email}.',
  deleteNote: 'Vos données seront supprimées sous 24 heures.',
  emailSubject: 'Votre résultat GriffoWork',
  emailHeading: 'Votre résultat est prêt',
  emailBodyMatches: 'Nous avons trouvé {count} opportunités qui correspondent à votre CV.',
  emailBodyOne: 'Nous avons trouvé 1 opportunité qui correspond à votre CV.',
  emailBodyNone: 'Nous avons lu votre CV et votre résultat est prêt.',
  emailCta: 'Voir mon résultat',
  emailDeleteNote: 'Vos données seront supprimées sous 24 heures, et le lien cessera de fonctionner avant.',
  emailKeepNote: 'Vous avez choisi de conserver votre CV pour que des entreprises puissent vous trouver. Pour le supprimer, répondez à cet e-mail.',
  emailIgnore: 'Si ce n’est pas vous qui l’avez envoyé, vous pouvez ignorer cet e-mail.',
}

const it: MatchPreviewCopy = {
  eyebrow: 'Gratis · senza registrazione',
  title: 'Cerchi lavoro?',
  lead: 'Invia il tuo curriculum e scopri le opportunità adatte a te.',
  subtitle: 'Confrontiamo il tuo curriculum con {N} offerte aperte e ti mostriamo dove sei adatto.',
  uploadCta: 'Scegli il curriculum in PDF',
  fileChosen: 'File: {name}',
  uploadHint: 'PDF fino a 5 MB',
  pasteToggle: 'Preferisco incollare il testo',
  pastePlaceholder: 'Incolla qui il testo del tuo curriculum…',
  emailLabel: 'La tua email',
  emailPlaceholder: 'tu@email.it',
  emailHint: 'Ti inviamo il link al risultato a questo indirizzo.',
  retentionTitle: 'Cosa facciamo con i tuoi dati',
  retentionDelete: 'Cancellare tutto entro 24 ore',
  retentionDeleteHint: 'Vedi il risultato e poi non conserviamo nulla.',
  retentionKeep: 'Conservare il mio curriculum perché le aziende possano trovarmi',
  retentionKeepHint: 'Viene conservato fino a 2 anni, e puoi chiederne la cancellazione quando vuoi.',
  privacyLink: 'Informativa sulla privacy',
  submitCta: 'Trova le mie opportunità',
  submitting: 'Invio del curriculum…',
  processing: 'Stiamo confrontando il tuo profilo con le offerte aperte…',
  processingHint: 'Ci vogliono pochi secondi. Non chiudere questa pagina.',
  errorEmail: 'Controlla l’indirizzo email.',
  errorFile: 'Scegli un PDF o incolla il testo del curriculum.',
  errorTooLarge: 'Il file supera i 5 MB.',
  errorNotPdf: 'Questo file non è un PDF valido.',
  errorRate: 'Troppi tentativi di seguito. Attendi qualche minuto.',
  errorGeneric: 'Qualcosa è andato storto da parte nostra. Riprova tra poco.',
  limitTitle: 'Hai già usato la ricerca gratuita di oggi',
  limitText: 'Crea il tuo account per continuare subito, oppure torna domani.',
  limitCta: 'Crea account',
  expiredText: 'Questo risultato è scaduto e i dati sono stati cancellati.',
  failedText: 'Non siamo riusciti a leggere il tuo curriculum in questo momento. Riprova tra poco.',
  retryCta: 'Invia di nuovo',
  resultTitleMany: 'Abbiamo trovato {count} opportunità adatte a te',
  resultTitleOne: 'Abbiamo trovato 1 opportunità adatta a te',
  resultTitleNone: 'Non abbiamo ancora trovato un’opportunità forte per il tuo profilo',
  resultNoneText: 'Le offerte cambiano ogni giorno. Con un account, il Radar ti avvisa quando ne compare una adatta a te.',
  profileInsufficientText: 'Nel curriculum non abbiamo individuato il tuo ruolo, il tuo settore o le tue competenze, quindi non c’è ancora niente da confrontare con le offerte.',
  freeBadge: 'Opportunità sbloccata',
  fit: {
    strong: 'Alta compatibilità',
    good: 'Buona compatibilità',
    partial: 'Compatibilità parziale',
    weak: 'Bassa compatibilità',
  },
  remote: { remote: 'Da remoto', hybrid: 'Ibrido', onsite: 'In sede' },
  publishedOn: 'Pubblicata il {date}',
  applyCta: 'Vedi l’offerta e candidati',
  applyNote: 'La candidatura si fa sul sito d’origine dell’offerta.',
  lockedTitle: 'Ci sono altre {count} opportunità per il tuo profilo',
  lockedTitleOne: 'C’è 1 altra opportunità per il tuo profilo',
  lockedStrong: '{n} con alta compatibilità',
  lockedStrongOne: 'con alta compatibilità',
  unlockCta: 'Vedi tutte le opportunità',
  atsScoreLabel: 'Leggibilità per i sistemi di selezione',
  teaserMany: 'Abbiamo trovato {n} punti che riducono la tua visibilità nei sistemi di selezione',
  teaserOne: 'Abbiamo trovato 1 punto che riduce la tua visibilità nei sistemi di selezione',
  teaserNone: 'I sistemi di selezione leggono bene il tuo curriculum.',
  teaserCategories: {
    keywords: '{n} in parole chiave e contenuto',
    formatting: '{n} nella formattazione',
    experience: '{n} in esperienza e formazione',
    contact: '{n} nei dati di contatto',
  },
  teaserClose: 'Correggerli può aumentare le tue possibilità di ricevere un invito a un colloquio.',
  teaserCta: 'Vedi la diagnosi completa',
  keptNote: 'Il tuo curriculum è stato conservato perché le aziende possano trovarti. Per cancellarlo, scrivi a {email}.',
  deleteNote: 'I tuoi dati saranno cancellati entro 24 ore.',
  emailSubject: 'Il tuo risultato su GriffoWork',
  emailHeading: 'Il tuo risultato è pronto',
  emailBodyMatches: 'Abbiamo trovato {count} opportunità adatte al tuo curriculum.',
  emailBodyOne: 'Abbiamo trovato 1 opportunità adatta al tuo curriculum.',
  emailBodyNone: 'Abbiamo letto il tuo curriculum e il risultato è pronto.',
  emailCta: 'Vedi il mio risultato',
  emailDeleteNote: 'I tuoi dati saranno cancellati entro 24 ore, e il link smette di funzionare prima.',
  emailKeepNote: 'Hai scelto di conservare il tuo curriculum perché le aziende possano trovarti. Per cancellarlo, rispondi a questa email.',
  emailIgnore: 'Se non sei stato tu a inviarlo, puoi ignorare questa email.',
}

const nl: MatchPreviewCopy = {
  eyebrow: 'Gratis · zonder account',
  title: 'Op zoek naar werk?',
  lead: 'Upload je cv en ontdek de kansen die bij je passen.',
  subtitle: 'We vergelijken je cv met {N} openstaande vacatures en laten zien waar je past.',
  uploadCta: 'Cv als pdf kiezen',
  fileChosen: 'Bestand: {name}',
  uploadHint: 'Pdf tot 5 MB',
  pasteToggle: 'Ik plak liever de tekst',
  pastePlaceholder: 'Plak hier de tekst van je cv…',
  emailLabel: 'Je e-mailadres',
  emailPlaceholder: 'jij@email.nl',
  emailHint: 'We sturen de link naar je resultaat naar dit adres.',
  retentionTitle: 'Wat we met je gegevens doen',
  retentionDelete: 'Alles binnen 24 uur verwijderen',
  retentionDeleteHint: 'Je ziet je resultaat en daarna bewaren we niets.',
  retentionKeep: 'Mijn cv bewaren zodat bedrijven me kunnen vinden',
  retentionKeepHint: 'Wordt maximaal 2 jaar bewaard, en je kunt altijd vragen om het te verwijderen.',
  privacyLink: 'Privacybeleid',
  submitCta: 'Mijn kansen vinden',
  submitting: 'Je cv wordt verstuurd…',
  processing: 'We vergelijken je profiel met de openstaande vacatures…',
  processingHint: 'Dit duurt een paar seconden. Sluit deze pagina niet.',
  errorEmail: 'Controleer je e-mailadres.',
  errorFile: 'Kies een pdf of plak de tekst van je cv.',
  errorTooLarge: 'Het bestand is groter dan 5 MB.',
  errorNotPdf: 'Dit bestand is geen geldige pdf.',
  errorRate: 'Te veel pogingen achter elkaar. Wacht een paar minuten.',
  errorGeneric: 'Er ging iets mis aan onze kant. Probeer het zo meteen opnieuw.',
  limitTitle: 'Je hebt de gratis zoekopdracht van vandaag al gebruikt',
  limitText: 'Maak een account aan om nu verder te gaan, of kom morgen terug.',
  limitCta: 'Account aanmaken',
  expiredText: 'Dit resultaat is verlopen en de gegevens zijn verwijderd.',
  failedText: 'We konden je cv nu niet lezen. Probeer het zo meteen opnieuw.',
  retryCta: 'Opnieuw versturen',
  resultTitleMany: 'We hebben {count} kansen gevonden die bij je passen',
  resultTitleOne: 'We hebben 1 kans gevonden die bij je past',
  resultTitleNone: 'We hebben nog geen sterke kans voor je profiel gevonden',
  resultNoneText: 'Vacatures veranderen elke dag. Met een account laat de Radar het je weten zodra er een verschijnt die bij je past.',
  profileInsufficientText: 'We konden in je cv je functie, je vakgebied of je vaardigheden niet vinden, dus er valt nog niets te vergelijken met de vacatures.',
  freeBadge: 'Vrijgegeven kans',
  fit: {
    strong: 'Hoge match',
    good: 'Goede match',
    partial: 'Gedeeltelijke match',
    weak: 'Lage match',
  },
  remote: { remote: 'Op afstand', hybrid: 'Hybride', onsite: 'Op locatie' },
  publishedOn: 'Geplaatst op {date}',
  applyCta: 'Vacature bekijken en solliciteren',
  applyNote: 'Je solliciteert op de oorspronkelijke website van de vacature.',
  lockedTitle: 'Er zijn nog {count} kansen voor jouw profiel',
  lockedTitleOne: 'Er is nog 1 kans voor jouw profiel',
  lockedStrong: 'waarvan {n} met een hoge match',
  lockedStrongOne: 'met een hoge match',
  unlockCta: 'Alle kansen bekijken',
  atsScoreLabel: 'Leesbaarheid voor selectiesystemen',
  teaserMany: 'We hebben {n} punten gevonden die je zichtbaarheid in selectiesystemen verminderen',
  teaserOne: 'We hebben 1 punt gevonden dat je zichtbaarheid in selectiesystemen vermindert',
  teaserNone: 'Selectiesystemen lezen je cv goed.',
  teaserCategories: {
    keywords: '{n} in trefwoorden en inhoud',
    formatting: '{n} in de opmaak',
    experience: '{n} in werkervaring en opleiding',
    contact: '{n} in contactgegevens',
  },
  teaserClose: 'Ze oplossen kan je kans op een uitnodiging voor een sollicitatiegesprek vergroten.',
  teaserCta: 'Volledige diagnose bekijken',
  keptNote: 'Je cv is bewaard zodat bedrijven je kunnen vinden. Om het te verwijderen, schrijf naar {email}.',
  deleteNote: 'Je gegevens worden binnen 24 uur verwijderd.',
  emailSubject: 'Je resultaat bij GriffoWork',
  emailHeading: 'Je resultaat staat klaar',
  emailBodyMatches: 'We hebben {count} kansen gevonden die bij je cv passen.',
  emailBodyOne: 'We hebben 1 kans gevonden die bij je cv past.',
  emailBodyNone: 'We hebben je cv gelezen en je resultaat staat klaar.',
  emailCta: 'Mijn resultaat bekijken',
  emailDeleteNote: 'Je gegevens worden binnen 24 uur verwijderd, en de link werkt daarvoor al niet meer.',
  emailKeepNote: 'Je hebt ervoor gekozen je cv te bewaren zodat bedrijven je kunnen vinden. Om het te verwijderen, beantwoord je deze e-mail.',
  emailIgnore: 'Heb jij dit niet verstuurd? Dan kun je deze e-mail negeren.',
}

const sv: MatchPreviewCopy = {
  eyebrow: 'Gratis · utan registrering',
  title: 'Letar du jobb?',
  lead: 'Skicka ditt CV och upptäck möjligheterna som passar dig.',
  subtitle: 'Vi jämför ditt CV med {N} lediga jobb och visar var du passar in.',
  uploadCta: 'Välj CV som PDF',
  fileChosen: 'Fil: {name}',
  uploadHint: 'PDF på upp till 5 MB',
  pasteToggle: 'Jag klistrar hellre in texten',
  pastePlaceholder: 'Klistra in texten från ditt CV här…',
  emailLabel: 'Din e-postadress',
  emailPlaceholder: 'du@epost.se',
  emailHint: 'Vi skickar länken till ditt resultat till den här adressen.',
  retentionTitle: 'Vad vi gör med dina uppgifter',
  retentionDelete: 'Radera allt inom 24 timmar',
  retentionDeleteHint: 'Du ser resultatet, och sedan sparar vi ingenting.',
  retentionKeep: 'Spara mitt CV så att företag kan hitta mig',
  retentionKeepHint: 'Sparas i upp till 2 år, och du kan när som helst be oss radera det.',
  privacyLink: 'Integritetspolicy',
  submitCta: 'Hitta mina möjligheter',
  submitting: 'Ditt CV skickas…',
  processing: 'Vi jämför din profil med de lediga jobben…',
  processingHint: 'Det tar några sekunder. Stäng inte den här sidan.',
  errorEmail: 'Kontrollera e-postadressen.',
  errorFile: 'Välj en PDF eller klistra in texten från ditt CV.',
  errorTooLarge: 'Filen är större än 5 MB.',
  errorNotPdf: 'Den här filen är inte en giltig PDF.',
  errorRate: 'För många försök i rad. Vänta några minuter.',
  errorGeneric: 'Något gick fel hos oss. Försök igen om en liten stund.',
  limitTitle: 'Du har redan använt dagens gratissökning',
  limitText: 'Skapa ett konto för att fortsätta nu, eller kom tillbaka i morgon.',
  limitCta: 'Skapa konto',
  expiredText: 'Det här resultatet har gått ut och uppgifterna har raderats.',
  failedText: 'Vi kunde inte läsa ditt CV just nu. Försök igen om en liten stund.',
  retryCta: 'Skicka igen',
  resultTitleMany: 'Vi hittade {count} möjligheter som passar dig',
  resultTitleOne: 'Vi hittade 1 möjlighet som passar dig',
  resultTitleNone: 'Vi har ännu inte hittat någon stark möjlighet för din profil',
  resultNoneText: 'Jobben ändras varje dag. Med ett konto meddelar Radar dig när ett som passar dyker upp.',
  profileInsufficientText: 'Vi hittade varken din befattning, ditt område eller dina kompetenser i ditt CV, så det finns ännu inget att jämföra med jobben.',
  freeBadge: 'Upplåst möjlighet',
  fit: {
    strong: 'Hög matchning',
    good: 'Bra matchning',
    partial: 'Delvis matchning',
    weak: 'Låg matchning',
  },
  remote: { remote: 'Distans', hybrid: 'Hybrid', onsite: 'På plats' },
  publishedOn: 'Publicerad {date}',
  applyCta: 'Se jobbet och ansök',
  applyNote: 'Du ansöker på jobbets ursprungliga webbplats.',
  lockedTitle: 'Det finns {count} fler möjligheter för din profil',
  lockedTitleOne: 'Det finns 1 möjlighet till för din profil',
  lockedStrong: 'varav {n} med hög matchning',
  lockedStrongOne: 'med hög matchning',
  unlockCta: 'Se alla möjligheter',
  atsScoreLabel: 'Läsbarhet för rekryteringssystem',
  teaserMany: 'Vi hittade {n} punkter som minskar din synlighet i rekryteringssystem',
  teaserOne: 'Vi hittade 1 punkt som minskar din synlighet i rekryteringssystem',
  teaserNone: 'Rekryteringssystem läser ditt CV bra.',
  teaserCategories: {
    keywords: '{n} i nyckelord och innehåll',
    formatting: '{n} i formateringen',
    experience: '{n} i erfarenhet och utbildning',
    contact: '{n} i kontaktuppgifter',
  },
  teaserClose: 'Att åtgärda dem kan öka dina chanser att bli kallad till intervju.',
  teaserCta: 'Se hela diagnosen',
  keptNote: 'Ditt CV har sparats så att företag kan hitta dig. Skriv till {email} för att radera det.',
  deleteNote: 'Dina uppgifter raderas inom 24 timmar.',
  emailSubject: 'Ditt resultat hos GriffoWork',
  emailHeading: 'Ditt resultat är klart',
  emailBodyMatches: 'Vi hittade {count} möjligheter som passar ditt CV.',
  emailBodyOne: 'Vi hittade 1 möjlighet som passar ditt CV.',
  emailBodyNone: 'Vi har läst ditt CV och ditt resultat är klart.',
  emailCta: 'Se mitt resultat',
  emailDeleteNote: 'Dina uppgifter raderas inom 24 timmar, och länken slutar fungera innan dess.',
  emailKeepNote: 'Du valde att spara ditt CV så att företag kan hitta dig. Svara på det här mejlet för att radera det.',
  emailIgnore: 'Om det inte var du som skickade det kan du ignorera det här mejlet.',
}

const ja: MatchPreviewCopy = {
  eyebrow: '無料・登録不要',
  title: '仕事をお探しですか？',
  lead: '履歴書を送るだけで、あなたに合う求人が見つかります。',
  subtitle: 'あなたの履歴書を {N} 件の募集中の求人と照合し、どこに合うかをお見せします。',
  uploadCta: '履歴書のPDFを選ぶ',
  fileChosen: 'ファイル: {name}',
  uploadHint: '5MBまでのPDF',
  pasteToggle: 'テキストを貼り付ける',
  pastePlaceholder: '履歴書のテキストをここに貼り付けてください…',
  emailLabel: 'メールアドレス',
  emailPlaceholder: 'you@example.jp',
  emailHint: '結果へのリンクをこのアドレスにお送りします。',
  retentionTitle: 'あなたのデータの扱い',
  retentionDelete: '24時間以内にすべて削除する',
  retentionDeleteHint: '結果をご覧いただいた後、データは一切保存しません。',
  retentionKeep: '企業に見つけてもらえるよう履歴書を保存する',
  retentionKeepHint: '最長2年間保存され、いつでも削除を依頼できます。',
  privacyLink: 'プライバシーポリシー',
  submitCta: '自分に合う求人を探す',
  submitting: '履歴書を送信しています…',
  processing: 'あなたのプロフィールを募集中の求人と照合しています…',
  processingHint: '数秒かかります。このページを閉じないでください。',
  errorEmail: 'メールアドレスをご確認ください。',
  errorFile: 'PDFを選ぶか、履歴書のテキストを貼り付けてください。',
  errorTooLarge: 'ファイルが5MBを超えています。',
  errorNotPdf: 'このファイルは有効なPDFではありません。',
  errorRate: '短時間に試行が多すぎます。数分お待ちください。',
  errorGeneric: 'こちらで問題が発生しました。しばらくしてからもう一度お試しください。',
  limitTitle: '本日の無料検索はすでにご利用済みです',
  limitText: '今すぐ続けるにはアカウントを作成するか、明日またお越しください。',
  limitCta: 'アカウントを作成',
  expiredText: 'この結果は有効期限が切れ、データは削除されました。',
  failedText: '現在、履歴書を読み取れませんでした。しばらくしてからもう一度お試しください。',
  retryCta: 'もう一度送る',
  resultTitleMany: 'あなたに合う求人が {count} 件見つかりました',
  resultTitleOne: 'あなたに合う求人が 1 件見つかりました',
  resultTitleNone: 'あなたのプロフィールに強く合う求人はまだ見つかっていません',
  resultNoneText: '求人は毎日変わります。アカウントがあれば、合う求人が出たときに Radar がお知らせします。',
  profileInsufficientText: '履歴書から職種・分野・スキルを読み取れなかったため、求人と照合できるものがまだありません。',
  freeBadge: '公開中の求人',
  fit: {
    strong: '適合度：高',
    good: '適合度：良',
    partial: '適合度：一部',
    weak: '適合度：低',
  },
  remote: { remote: 'リモート', hybrid: 'ハイブリッド', onsite: '出社' },
  publishedOn: '掲載日 {date}',
  applyCta: '求人を見て応募する',
  applyNote: '応募は求人の掲載元サイトで行います。',
  lockedTitle: 'あなたのプロフィールに合う求人がほかに {count} 件あります',
  lockedTitleOne: 'あなたのプロフィールに合う求人がほかに 1 件あります',
  lockedStrong: 'うち {n} 件は適合度が高い求人です',
  lockedStrongOne: '適合度が高い求人です',
  unlockCta: 'すべての求人を見る',
  atsScoreLabel: '採用管理システムでの読みやすさ',
  teaserMany: '採用管理システムでの見つけやすさを下げている点が {n} 件見つかりました',
  teaserOne: '採用管理システムでの見つけやすさを下げている点が 1 件見つかりました',
  teaserNone: 'あなたの履歴書は採用管理システムで問題なく読み取れます。',
  teaserCategories: {
    keywords: 'キーワードと内容で {n} 件',
    formatting: 'レイアウトで {n} 件',
    experience: '職歴と学歴で {n} 件',
    contact: '連絡先で {n} 件',
  },
  teaserClose: 'これらを直すことで、面接に呼ばれる可能性が高まることがあります。',
  teaserCta: '詳しい診断を見る',
  keptNote: '企業に見つけてもらえるよう、履歴書を保存しました。削除するには {email} までご連絡ください。',
  deleteNote: 'あなたのデータは24時間以内に削除されます。',
  emailSubject: 'GriffoWork の結果',
  emailHeading: '結果の準備ができました',
  emailBodyMatches: 'あなたの履歴書に合う求人が {count} 件見つかりました。',
  emailBodyOne: 'あなたの履歴書に合う求人が 1 件見つかりました。',
  emailBodyNone: '履歴書を読み取り、結果の準備ができました。',
  emailCta: '結果を見る',
  emailDeleteNote: 'あなたのデータは24時間以内に削除され、リンクはそれより前に無効になります。',
  emailKeepNote: '企業に見つけてもらえるよう、履歴書の保存を選択されました。削除するには、このメールに返信してください。',
  emailIgnore: 'お心当たりがない場合は、このメールを無視してください。',
}

const ko: MatchPreviewCopy = {
  eyebrow: '무료 · 가입 불필요',
  title: '일자리를 찾고 계신가요?',
  lead: '이력서를 보내고 나에게 맞는 기회를 찾아보세요.',
  subtitle: '이력서를 채용 중인 공고 {N}건과 비교해 어디에 맞는지 보여드립니다.',
  uploadCta: '이력서 PDF 선택',
  fileChosen: '파일: {name}',
  uploadHint: '5MB 이하 PDF',
  pasteToggle: '텍스트를 붙여넣을게요',
  pastePlaceholder: '이력서 내용을 여기에 붙여넣으세요…',
  emailLabel: '이메일',
  emailPlaceholder: 'you@email.com',
  emailHint: '결과 링크를 이 주소로 보내드립니다.',
  retentionTitle: '데이터 처리 방식',
  retentionDelete: '24시간 이내에 모두 삭제',
  retentionDeleteHint: '결과를 확인한 뒤에는 아무것도 보관하지 않습니다.',
  retentionKeep: '기업이 나를 찾을 수 있도록 이력서 보관',
  retentionKeepHint: '최대 2년간 보관되며, 언제든 삭제를 요청할 수 있습니다.',
  privacyLink: '개인정보처리방침',
  submitCta: '나에게 맞는 기회 찾기',
  submitting: '이력서를 보내는 중…',
  processing: '프로필을 채용 중인 공고와 비교하는 중…',
  processingHint: '몇 초 정도 걸립니다. 이 페이지를 닫지 마세요.',
  errorEmail: '이메일 주소를 확인해 주세요.',
  errorFile: 'PDF를 선택하거나 이력서 내용을 붙여넣어 주세요.',
  errorTooLarge: '파일이 5MB를 넘습니다.',
  errorNotPdf: '올바른 PDF 파일이 아닙니다.',
  errorRate: '연속 시도가 너무 많습니다. 몇 분 후에 다시 시도해 주세요.',
  errorGeneric: '문제가 발생했습니다. 잠시 후 다시 시도해 주세요.',
  limitTitle: '오늘의 무료 검색을 이미 사용하셨습니다',
  limitText: '지금 계속하려면 계정을 만들거나 내일 다시 방문해 주세요.',
  limitCta: '계정 만들기',
  expiredText: '이 결과는 만료되어 데이터가 삭제되었습니다.',
  failedText: '지금은 이력서를 읽을 수 없었습니다. 잠시 후 다시 시도해 주세요.',
  retryCta: '다시 보내기',
  resultTitleMany: '나에게 맞는 기회를 {count}건 찾았습니다',
  resultTitleOne: '나에게 맞는 기회를 1건 찾았습니다',
  resultTitleNone: '아직 프로필에 잘 맞는 기회를 찾지 못했습니다',
  resultNoneText: '채용 공고는 매일 바뀝니다. 계정이 있으면 맞는 공고가 나올 때 Radar가 알려드립니다.',
  profileInsufficientText: '이력서에서 직무, 분야, 역량을 확인하지 못해 아직 공고와 비교할 내용이 없습니다.',
  freeBadge: '공개된 기회',
  fit: {
    strong: '적합도 높음',
    good: '적합도 좋음',
    partial: '부분 적합',
    weak: '적합도 낮음',
  },
  remote: { remote: '원격', hybrid: '하이브리드', onsite: '출근' },
  publishedOn: '게시일 {date}',
  applyCta: '공고 보고 지원하기',
  applyNote: '지원은 공고의 원래 사이트에서 진행됩니다.',
  lockedTitle: '내 프로필에 맞는 기회가 {count}건 더 있습니다',
  lockedTitleOne: '내 프로필에 맞는 기회가 1건 더 있습니다',
  lockedStrong: '그중 {n}건은 적합도가 높습니다',
  lockedStrongOne: '적합도가 높은 기회입니다',
  unlockCta: '모든 기회 보기',
  atsScoreLabel: '채용 관리 시스템 가독성',
  teaserMany: '채용 관리 시스템에서 이력서가 잘 보이지 않게 만드는 요소 {n}개를 찾았습니다',
  teaserOne: '채용 관리 시스템에서 이력서가 잘 보이지 않게 만드는 요소 1개를 찾았습니다',
  teaserNone: '채용 관리 시스템이 이력서를 잘 읽습니다.',
  teaserCategories: {
    keywords: '키워드와 내용 {n}개',
    formatting: '서식 {n}개',
    experience: '경력과 학력 {n}개',
    contact: '연락처 {n}개',
  },
  teaserClose: '이를 고치면 면접 기회가 늘어날 수 있습니다.',
  teaserCta: '전체 진단 보기',
  keptNote: '기업이 찾을 수 있도록 이력서를 보관했습니다. 삭제하려면 {email}로 연락해 주세요.',
  deleteNote: '데이터는 24시간 이내에 삭제됩니다.',
  emailSubject: 'GriffoWork 결과',
  emailHeading: '결과가 준비되었습니다',
  emailBodyMatches: '이력서에 맞는 기회를 {count}건 찾았습니다.',
  emailBodyOne: '이력서에 맞는 기회를 1건 찾았습니다.',
  emailBodyNone: '이력서를 읽었고 결과가 준비되었습니다.',
  emailCta: '내 결과 보기',
  emailDeleteNote: '데이터는 24시간 이내에 삭제되며, 링크는 그 전에 만료됩니다.',
  emailKeepNote: '기업이 찾을 수 있도록 이력서 보관을 선택하셨습니다. 삭제하려면 이 이메일에 회신해 주세요.',
  emailIgnore: '본인이 보낸 것이 아니라면 이 이메일을 무시하셔도 됩니다.',
}

const zh: MatchPreviewCopy = {
  eyebrow: '免费 · 无需注册',
  title: '正在找工作？',
  lead: '上传简历，发现适合你的机会。',
  subtitle: '我们将你的简历与 {N} 个在招职位进行比对，告诉你适合哪里。',
  uploadCta: '选择 PDF 简历',
  fileChosen: '文件：{name}',
  uploadHint: '不超过 5 MB 的 PDF',
  pasteToggle: '我想粘贴文字',
  pastePlaceholder: '在这里粘贴你的简历内容…',
  emailLabel: '你的邮箱',
  emailPlaceholder: 'you@email.com',
  emailHint: '我们会把结果链接发到这个邮箱。',
  retentionTitle: '我们如何处理你的数据',
  retentionDelete: '24 小时内全部删除',
  retentionDeleteHint: '你查看结果后，我们不保留任何数据。',
  retentionKeep: '保存我的简历，让企业可以找到我',
  retentionKeepHint: '最多保存 2 年，你可以随时要求删除。',
  privacyLink: '隐私政策',
  submitCta: '寻找我的机会',
  submitting: '正在上传简历…',
  processing: '正在将你的资料与在招职位进行比对…',
  processingHint: '只需几秒钟，请不要关闭此页面。',
  errorEmail: '请检查邮箱地址。',
  errorFile: '请选择 PDF 或粘贴简历内容。',
  errorTooLarge: '文件超过 5 MB。',
  errorNotPdf: '该文件不是有效的 PDF。',
  errorRate: '连续尝试次数过多，请等几分钟再试。',
  errorGeneric: '我们这边出了问题，请稍后再试。',
  limitTitle: '你今天已经用过免费搜索了',
  limitText: '现在创建账户即可继续，或者明天再来。',
  limitCta: '创建账户',
  expiredText: '此结果已过期，数据已删除。',
  failedText: '暂时无法读取你的简历，请稍后再试。',
  retryCta: '重新上传',
  resultTitleMany: '我们找到了 {count} 个适合你的机会',
  resultTitleOne: '我们找到了 1 个适合你的机会',
  resultTitleNone: '暂时还没有找到与你的资料高度匹配的机会',
  resultNoneText: '职位每天都在变化。有了账户，Radar 会在出现合适职位时通知你。',
  profileInsufficientText: '我们没能从简历中识别出你的职位、领域或技能，因此暂时还无法与职位进行比对。',
  freeBadge: '已开放的机会',
  fit: {
    strong: '高度匹配',
    good: '较好匹配',
    partial: '部分匹配',
    weak: '匹配度低',
  },
  remote: { remote: '远程', hybrid: '混合办公', onsite: '现场办公' },
  publishedOn: '发布于 {date}',
  applyCta: '查看职位并申请',
  applyNote: '申请在职位的原始网站上完成。',
  lockedTitle: '还有 {count} 个适合你的机会',
  lockedTitleOne: '还有 1 个适合你的机会',
  lockedStrong: '其中 {n} 个高度匹配',
  lockedStrongOne: '而且高度匹配',
  unlockCta: '查看所有机会',
  atsScoreLabel: '招聘筛选系统可读性',
  teaserMany: '我们发现 {n} 处降低你在招聘筛选系统中可见度的问题',
  teaserOne: '我们发现 1 处降低你在招聘筛选系统中可见度的问题',
  teaserNone: '招聘筛选系统可以顺利读取你的简历。',
  teaserCategories: {
    keywords: '关键词与内容 {n} 处',
    formatting: '格式 {n} 处',
    experience: '工作经历与教育背景 {n} 处',
    contact: '联系方式 {n} 处',
  },
  teaserClose: '修正这些问题可能会提高你获得面试邀请的机会。',
  teaserCta: '查看完整诊断',
  keptNote: '你的简历已保存，让企业可以找到你。如需删除，请写信至 {email}。',
  deleteNote: '你的数据将在 24 小时内删除。',
  emailSubject: '你的 GriffoWork 结果',
  emailHeading: '你的结果已经准备好了',
  emailBodyMatches: '我们找到了 {count} 个与你简历相符的机会。',
  emailBodyOne: '我们找到了 1 个与你简历相符的机会。',
  emailBodyNone: '我们已读取你的简历，结果已经准备好了。',
  emailCta: '查看我的结果',
  emailDeleteNote: '你的数据将在 24 小时内删除，链接会在此之前失效。',
  emailKeepNote: '你选择了保存简历以便企业找到你。如需删除，请回复此邮件。',
  emailIgnore: '如果不是你本人提交的，请忽略此邮件。',
}

const ar: MatchPreviewCopy = {
  eyebrow: 'مجانًا · دون تسجيل',
  title: 'تبحث عن عمل؟',
  lead: 'أرسل سيرتك الذاتية واكتشف الفرص التي تناسبك.',
  subtitle: 'نقارن سيرتك الذاتية مع {N} وظيفة شاغرة ونُريك أين تناسب.',
  uploadCta: 'اختر السيرة الذاتية بصيغة PDF',
  fileChosen: 'الملف: {name}',
  uploadHint: 'ملف PDF حتى 5 ميغابايت',
  pasteToggle: 'أفضّل لصق النص',
  pastePlaceholder: 'الصق نص سيرتك الذاتية هنا…',
  emailLabel: 'بريدك الإلكتروني',
  emailPlaceholder: 'you@email.com',
  emailHint: 'سنرسل رابط النتيجة إلى هذا العنوان.',
  retentionTitle: 'ماذا نفعل ببياناتك',
  retentionDelete: 'حذف كل شيء خلال 24 ساعة',
  retentionDeleteHint: 'ترى النتيجة، ثم لا نحتفظ بأي شيء.',
  retentionKeep: 'الاحتفاظ بسيرتي الذاتية كي تتمكن الشركات من العثور عليّ',
  retentionKeepHint: 'تُحفظ لمدة تصل إلى سنتين، ويمكنك طلب حذفها في أي وقت.',
  privacyLink: 'سياسة الخصوصية',
  submitCta: 'اعثر على فرصي',
  submitting: 'جارٍ إرسال سيرتك الذاتية…',
  processing: 'نقارن ملفك مع الوظائف الشاغرة…',
  processingHint: 'يستغرق الأمر بضع ثوانٍ. لا تغلق هذه الصفحة.',
  errorEmail: 'تحقّق من البريد الإلكتروني.',
  errorFile: 'اختر ملف PDF أو الصق نص سيرتك الذاتية.',
  errorTooLarge: 'حجم الملف يتجاوز 5 ميغابايت.',
  errorNotPdf: 'هذا الملف ليس PDF صالحًا.',
  errorRate: 'محاولات كثيرة متتالية. انتظر بضع دقائق.',
  errorGeneric: 'حدث خطأ من جهتنا. حاول مرة أخرى بعد قليل.',
  limitTitle: 'لقد استخدمت البحث المجاني لهذا اليوم',
  limitText: 'أنشئ حسابك للمتابعة الآن، أو عُد غدًا.',
  limitCta: 'إنشاء حساب',
  expiredText: 'انتهت صلاحية هذه النتيجة وحُذفت البيانات.',
  failedText: 'لم نتمكن من قراءة سيرتك الذاتية الآن. حاول مرة أخرى بعد قليل.',
  retryCta: 'إرسال مرة أخرى',
  resultTitleMany: 'وجدنا {count} فرصة تناسبك',
  resultTitleOne: 'وجدنا فرصة واحدة تناسبك',
  resultTitleNone: 'لم نجد بعد فرصة قوية تناسب ملفك',
  resultNoneText: 'الوظائف تتغير كل يوم. مع حساب، يُبلغك Radar عندما تظهر وظيفة تناسبك.',
  profileInsufficientText: 'لم نتمكن من تحديد مسمّاك الوظيفي أو مجالك أو مهاراتك في السيرة الذاتية، لذا لا يوجد بعد ما نقارنه بالوظائف.',
  freeBadge: 'فرصة متاحة',
  fit: {
    strong: 'توافق عالٍ',
    good: 'توافق جيد',
    partial: 'توافق جزئي',
    weak: 'توافق منخفض',
  },
  remote: { remote: 'عن بُعد', hybrid: 'هجين', onsite: 'من المقر' },
  publishedOn: 'نُشرت في {date}',
  applyCta: 'عرض الوظيفة والتقديم',
  applyNote: 'يتم التقديم على الموقع الأصلي للوظيفة.',
  lockedTitle: 'هناك {count} فرصة أخرى تناسب ملفك',
  lockedTitleOne: 'هناك فرصة أخرى واحدة تناسب ملفك',
  lockedStrong: 'منها {n} بتوافق عالٍ',
  lockedStrongOne: 'وهي بتوافق عالٍ',
  unlockCta: 'عرض كل الفرص',
  atsScoreLabel: 'قابلية القراءة في أنظمة الفرز',
  teaserMany: 'وجدنا {n} نقاط تقلّل من ظهورك في أنظمة الفرز',
  teaserOne: 'وجدنا نقطة واحدة تقلّل من ظهورك في أنظمة الفرز',
  teaserNone: 'أنظمة الفرز تقرأ سيرتك الذاتية جيدًا.',
  teaserCategories: {
    keywords: '{n} في الكلمات المفتاحية والمحتوى',
    formatting: '{n} في التنسيق',
    experience: '{n} في الخبرة والتعليم',
    contact: '{n} في بيانات الاتصال',
  },
  teaserClose: 'تصحيحها قد يزيد فرص دعوتك إلى مقابلة.',
  teaserCta: 'عرض التشخيص الكامل',
  keptNote: 'حُفظت سيرتك الذاتية كي تتمكن الشركات من العثور عليك. لحذفها، راسلنا على {email}.',
  deleteNote: 'ستُحذف بياناتك خلال 24 ساعة.',
  emailSubject: 'نتيجتك في GriffoWork',
  emailHeading: 'نتيجتك جاهزة',
  emailBodyMatches: 'وجدنا {count} فرصة تناسب سيرتك الذاتية.',
  emailBodyOne: 'وجدنا فرصة واحدة تناسب سيرتك الذاتية.',
  emailBodyNone: 'قرأنا سيرتك الذاتية ونتيجتك جاهزة.',
  emailCta: 'عرض نتيجتي',
  emailDeleteNote: 'ستُحذف بياناتك خلال 24 ساعة، ويتوقف الرابط عن العمل قبل ذلك.',
  emailKeepNote: 'اخترت الاحتفاظ بسيرتك الذاتية كي تتمكن الشركات من العثور عليك. لحذفها، ردّ على هذه الرسالة.',
  emailIgnore: 'إذا لم تكن أنت من أرسلها، يمكنك تجاهل هذه الرسالة.',
}

export const MATCH_PREVIEW_COPY: Record<Language, MatchPreviewCopy> = {
  pt, en, es, de, fr, it, ja, nl, sv, zh, ar, ko,
}

export function matchPreviewCopy(lang: string | null | undefined): MatchPreviewCopy {
  return MATCH_PREVIEW_COPY[lang as Language] ?? MATCH_PREVIEW_COPY.en
}

/** Troca `{chave}` pelo valor. Chave sem valor fica como está, para aparecer no teste. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, key) => (key in values ? String(values[key]) : whole))
}
